// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoJs8DBpX1C1Kg0DcQKfMSemiLv_obRoA',
    appId: '1:116487578887:android:f83d9d227fa78c1d7a91a2',
    messagingSenderId: '116487578887',
    projectId: 'tictic-info-11',
    storageBucket: 'tictic-info-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxvOfYqTwXN9wY2JyUAAIYqrdlWCMqh6k',
    appId: '1:116487578887:ios:120e1e7a124e422e7a91a2',
    messagingSenderId: '116487578887',
    projectId: 'tictic-info-11',
    storageBucket: 'tictic-info-11.firebasestorage.app',
    iosBundleId: 'com.example.ticticInfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxvOfYqTwXN9wY2JyUAAIYqrdlWCMqh6k',
    appId: '1:116487578887:ios:e6b22afa0ee24ce77a91a2',
    messagingSenderId: '116487578887',
    projectId: 'tictic-info-11',
    storageBucket: 'tictic-info-11.firebasestorage.app',
    iosBundleId: 'be.hepl.ticticinfo-11',
  );
}
